% ReadTannerGraph.m 
% 
% Author: Hatef Monajemi
% Date: Oct 26 2012
% 
% Description: 
% This program reads the *.txt file that 
% is generated by the PEG code of Hu . 
% Example of use: 
% A = ReadTannerGraph('RegGraph.txt')
% A is a sparse matrix.

function A = ReadTannerGraph(fname)


fid = fopen(fname,'rt');
N = textscan(fid, '%d', 1);
n = textscan(fid, '%d', 1);
k = textscan(fid, '%d', 1);
I = textscan(fid, '%d');
fclose(fid);

N = double(N{1});
n = double(n{1});
k = double(k{1});
I = reshape(I{1}, k, n);
I = I';


total_nnz = 0;
for i=1:n
   inds{i}   = I(i,I(i,:)~=0);
   total_nnz = total_nnz + size(inds{i},2);
end

row=zeros(1,total_nnz);
col=zeros(1,total_nnz);
val=zeros(1,total_nnz);

counter = 0;
for i = 1:n
   for j = 1:size(inds{i},2)
       counter = counter+1;
       row(counter) = i;
       col(counter) = inds{i}(j); 
   end
end  

A = sparse(row,col,ones(1,total_nnz),n,N);


